tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "asdf"
brew "cmatrix"
brew "docker", link: false
brew "doctl"
brew "figlet"
brew "gh"
brew "git"
brew "gnutls"
brew "gnupg"
brew "helm"
brew "htop"
brew "k9s"
brew "libpq", link: true
brew "mas"
brew "pnpm"
brew "starship"
brew "subversion"
brew "tig"
brew "trash"
brew "yarn"
brew "z"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "alfred"
cask "browserstacklocal"
cask "choosy"
cask "discord"
cask "docker"
cask "fig"
cask "firefox"
cask "firefox-developer-edition"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "gog-galaxy"
cask "google-chrome"
cask "hyper"
cask "insomnia"
cask "iterm2-beta"
cask "jetbrains-toolbox"
cask "lens"
cask "megasync"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "steelseries-exactmouse-tool"
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "Hidden Bar", id: 1452453066
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
