tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "coreutils"
brew "asdf"
brew "brew-cask-completion"
brew "glib"
brew "pkg-config"
brew "emacs"
brew "cask"
brew "circleci"
brew "cmake"
brew "cmatrix"
brew "cocoapods"
brew "deno"
brew "dive"
brew "doctl"
brew "duti"
brew "gh"
brew "gifsicle"
brew "git"
brew "gnupg"
brew "htop"
brew "hub"
brew "kubernetes-cli", link: false
brew "mas"
brew "mysql"
brew "mysql@5.7"
brew "postgresql"
brew "redis", restart_service: true
brew "starship"
brew "tig"
brew "tldr"
brew "tmux"
brew "v8"
brew "v8@3.15"
brew "watchman"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
cask "1password-beta"
cask "adobe-creative-cloud"
cask "alfred"
cask "android-studio"
cask "brave-browser"
cask "browserstacklocal"
cask "choosy"
cask "discord"
cask "docker"
cask "firefox"
cask "firefox-developer-edition"
cask "font-cascadia-code"
cask "font-caskaydia-cove-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrainsmono-nerd-font"
cask "font-noto-sans"
cask "font-roboto"
cask "gog-galaxy"
cask "google-chrome"
cask "insomnia"
cask "iterm2-beta"
cask "lens"
cask "logitech-camera-settings"
cask "macupdater"
cask "microsoft-auto-update"
cask "microsoft-edge-dev"
cask "microsoft-teams"
cask "nova"
cask "postgres"
cask "slack"
cask "spotify"
cask "steam"
cask "steelseries-exactmouse-tool"
cask "tableplus"
cask "transmit"
cask "visual-studio-code"
cask "windscribe"
mas "Bitwarden", id: 1352778147
mas "Contrast", id: 1254981365
mas "DaisyDisk", id: 411643860
mas "Frank DeLoupe", id: 530458789
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LittleIpsum", id: 405772121
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Valet Car Control", id: 1438609932
mas "Xcode", id: 497799835
