add_newline = false

format = """\
    $character\
    $directory\
    $username\
    $hostname\
    $kubernetes\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $java\
    $julia\
    $nim\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $crystal\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $time\
    """

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[directory]
style = "bold white"

[docker_context]
disabled = false

[git_branch]
style = "bold yellow"

[line_break]
disabled = true
