format = "$character$directory$all"
add_newline = false
command_timeout = 5000

[aws]
disabled = true

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"

[deno]
style = "bold black"
symbol = "󰯶 "

[directory]
style = "bold white"

[docker_context]
disabled = false

[git_branch]
style = "bold yellow"

[line_break]
disabled = true

[nodejs]
detect_extensions = []
detect_files = [".node-version", ".nvmrc"]
detect_folders = []
