[sudo.hosts]
"thebeast" = "pass://Personal/TheBeast/User Password"
"theserver" = "pass://Personal/TheServer/User Password"
"mosermacbookpro" = "pass://Moser Consulting/Moser Macbook Pro/User Password"
